[package]
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"
name = "usb-list"
version = "0.1.0"

[dependencies]
consts = { path = "../../advanced/common/consts" }
rusb = "0.5.5"
